import { fetchSuperAdminAuditLogs } from "@/super-admin/superAdminService";
import { ClipboardList } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
export function AuditLogs() {
    const [logs, setLogs] = useState([]);
    const [loading, setLoading] = useState(true);
    useEffect(() => { void fetchSuperAdminAuditLogs().then(setLogs).catch((error) => toast.error(error instanceof Error ? error.message : "Unable to load audit logs.")).finally(() => setLoading(false)); }, []);
    return <div className="audit-logs-container"><header className="audit-logs-header"><p className="audit-logs-super-admin">Super Admin</p><h1 className="audit-logs-audit-logs">Audit Logs</h1><p className="audit-logs-text">Real administrative activity recorded by AptFindr.</p></header><section className="audit-logs-section">{loading ? <div className="audit-logs-loading-audit-logs">Loading audit logs...</div> : logs.length === 0 ? <div className="audit-logs-content"><ClipboardList className="audit-logs-clipboard-list-icon"/><h2 className="audit-logs-no-audit-records-yet">No audit records yet</h2><p className="audit-logs-text">Important administrative actions will appear here when recorded.</p></div> : <div className="audit-logs-panel"><table className="audit-logs-table"><thead className="audit-logs-thead"><tr><th className="audit-logs-admin">Admin</th><th className="audit-logs-action">Action</th><th className="audit-logs-target">Target</th><th className="audit-logs-date-amp-time">Date &amp; Time</th></tr></thead><tbody className="audit-logs-tbody">{logs.map((log) => <tr key={String(log.id)} className="audit-logs-tr"><td className="audit-logs-td">{String(log.admin_id ?? "System")}</td><td className="audit-logs-td-2">{String(log.action ?? "Administrative action").replace(/_/g, " ")}</td><td className="audit-logs-td-3">{String(log.target_type ?? "—")}{log.target_id ? ` · ${String(log.target_id)}` : ""}</td><td className="audit-logs-td-3">{log.created_at ? new Date(log.created_at).toLocaleString("en-PH") : "—"}</td></tr>)}</tbody></table></div>}</section></div>;
}
